#!/bin/bash
###---IMPORTS---###
source $HOME/.cache/wal/colors.sh

bspc rule -r "*"

###---Autostart---###
sxhkd &
xrandr --output DP-4 --mode 1920x1080 --rotate normal --primary --output DVI-0 --rotate normal --left-of DP-4 &
$HOME/.config/polybar/launch.sh &
killall rclone
rclone --vfs-cache-mode writes mount onedrive: ~/onedrive &
picom &
wal -si $HOME/pictures/daily/1920x1080 &

###---MONITORS---###
bspc monitor DP-4 -d 1 2 3 4 5
bspc monitor DVI-I-0 -d 6 7 8 9 0

###---Global Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color	$background
bspc config active_border_color	$background
bspc config focused_border_color $foreground
bspc config presel_feedback_color	$background
bspc config urgent_border_color $background

bspc config single_monocle true
bspc config gapless_monocle true

###---Monitor And Desktop Settings----###
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 10
